name: Deploy matelab to GitHub pages

on:
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
        cache: pip
        cache-dependency-path: requirements.txt
    - run: pip install -r requirements.txt
    
    - name: Build
      run: python ./build.py

    - name: Upload files to GitHub Pages
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: 'output'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
